name: java-agent

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: gradle cache
      uses: actions/cache@v2
      env:
        cache-name: gradle
      with:
        path: .gradle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build.gradle', '**/settings.gradle', './gradlew', '**/gradle/wrapper/*') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}

    - name: build
      run: pwd && ls -la && ../gradlew shadowJar && pwd && ls -la